name: Java launch4j

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'oracle'
        java-version: '22'
              
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Test with Gradle
      run: ./gradlew test

    - name: Build with Gradle
      run: ./gradlew createExe

    - name: Upload test report artifact
      if: failure()
      uses: actions/upload-artifact@v4
      id: upload_report_v4
      with:
        name: Test-Report
        path: build/reports/tests/test
      continue-on-error: true

    - name: Upload build artifact
      if: success()
      uses: actions/upload-artifact@v4
      id: upload_unsigned_v4
      with:
        name: Invaders-SDP
        path: build/launch4j/*
      continue-on-error: true